version: "3.8"
services:
  main:
    build: .
    container_name: hey-special-container
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/hey-special
      - /hey-special/node_modules